name: Publish
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        run: actions/checkout@v4
      - name: Print
        run: echo Hallo
